### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by jdsutton** [kalbhor/MusicRepair#12]
Using linux mint 18 cinnamon 64-bit, Python 2.7.12

```
$ pip install musicrepair
$ cd Music
$ musicrepair

The Guess Who No sugar tonight - new mother nature.mp3 Adding metadata
*Finding metadata from Spotify.
*Trying to extract album art from Google.com
     >Added Album Art

     [*]Song name : No Sugar Tonight / New Mother Nature 
     [*]Artist : The Guess Who 
     [*]Album : The Essential The Guess Who 
 
Traceback (most recent call last):
  File "/usr/local/bin/musicrepair", line 11, in <module>
    load_entry_point('musicrepair==4.3', 'console_scripts', 'musicrepair')()
  File "/usr/local/lib/python2.7/dist-packages/musicrepair/command_line.py", line 324, in main
    fix_music(optional_arg)
  File "/usr/local/lib/python2.7/dist-packages/musicrepair/command_line.py", line 278, in fix_music
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
```

**Comment by kalbhor** [comment]
I have changed that exception statement now, try upgrading musicrepair to see if the error still persists.
