### ISSUE TITLE
HeaderNotFoundError

### ISSUE THREAD

**Issue by jdsutton** [kalbhor/MusicRepair#13]
Using linux mint and Python 3.5.2

```
No Sugar Tonight / New Mother Nature already has tags 
Relax already has tags 
Love Runs Out already has tags 
Traceback (most recent call last):
  File "/usr/local/bin/musicrepair", line 9, in <module>
    load_entry_point('musicrepair==4.3', 'console_scripts', 'musicrepair')()
  File "/usr/local/lib/python3.5/dist-packages/musicrepair/command_line.py", line 324, in main
    fix_music(optional_arg)
  File "/usr/local/lib/python3.5/dist-packages/musicrepair/command_line.py", line 232, in fix_music
    tags = File(file_name)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/_util.py", line 131, in wrapper_func
    return func(h, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/_file.py", line 295, in File
    return Kind(fileobj, filename=filething.filename)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/_util.py", line 123, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/id3/_file.py", line 406, in load
    self.info = self._Info(fileobj, offset)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/_util.py", line 152, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mutagen/mp3/__init__.py", line 387, in __init__
    raise HeaderNotFoundError("can't sync to MPEG frame")
mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame
```

**Comment by kalbhor** [comment]
On what file did this error get raised?

**Comment by jdsutton** [comment]
Not sure, I have a ton of files in the target folder.

**Comment by kalbhor** [comment]
Try upgrading musicrepair and let me know if the error persists.
