### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'keys'

### ISSUE THREAD

**Issue by soenkekluth** [kalbhor/MusicRepair#16]
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/2.7.12/bin/musicrepair", line 11, in <module>
    load_entry_point('musicrepair==4.4', 'console_scripts', 'musicrepair')()
  File "/usr/local/var/pyenv/versions/2.7.12/lib/python2.7/site-packages/musicrepair/command_line.py", line 338, in main
    fix_music(rename_format, optional_arg)
  File "/usr/local/var/pyenv/versions/2.7.12/lib/python2.7/site-packages/musicrepair/command_line.py", line 246, in fix_music
    albumart = albumsearch.img_search_bing(album)
  File "/usr/local/var/pyenv/versions/2.7.12/lib/python2.7/site-packages/musicrepair/albumsearch.py", line 24, in img_search_bing
    with open("keys") as f:
IOError: [Errno 2] No such file or directory: 'keys'

**Comment by bbruno** [comment]
Same issue.
Tried on different folder (with different mp3).

**Comment by kalbhor** [comment]
Please try upgrading musicrepair `pip install musicrepair -U` and let me know if the problem still occurs.

**Comment by gwalarn** [comment]
Sorry, Same issue after "pip install musicrepair -U"
Do you need more info (I use debian jessie) ?
Thanks

**Comment by kalbhor** [comment]
@gwalarn I'd like to see more details, send me the entire log on your terminal

**Comment by gwalarn** [comment]
$ cd /tmp
$ musicrepair -d ~/Musique/Arnold-La_Belle


........................

Arnold-Pourquoi_tu_pars.mp3
> Adding metadata
Traceback (most recent call last):
  File "/usr/local/bin/musicrepair", line 9, in <module>
    load_entry_point('musicrepair==4.5', 'console_scripts', 'musicrepair')()
  File "/usr/local/lib/python2.7/dist-packages/musicrepair/command_line.py", line 396, in main
    fix_music(arg_rename_format, norename=arg_norename)
  File "/usr/local/lib/python2.7/dist-packages/musicrepair/command_line.py", line 289, in fix_music
    albumart = albumsearch.img_search_bing(album)
  File "/usr/local/lib/python2.7/dist-packages/musicrepair/albumsearch.py", line 24, in img_search_bing
    with open("keys") as f:
IOError: [Errno 2] No such file or directory: 'keys'
$

**Comment by kalbhor** [comment]
I have made changes. Upgrade musicrepair and try again. `pip install musicrepair -U`
You should have version 4.6

**Comment by gwalarn** [comment]
Thanks, it work's fine with version 4.6

**Comment by soenkekluth** [comment]
:thumbsup:
