### ISSUE TITLE
Doesn't work on linux (LinuxMint 17.3)

### ISSUE THREAD

**Issue by jerrywham** [kalbhor/MusicRepair#20]
After the command `musicrepair`, this is what the console output : 
```bash
Swing Du Nul (live).mp3
> Adding metadata
    * Could not add album art
........................

Mercedes benz.mp3
> Adding metadata
    * Could not add album art
........................

Mountains o'things (live).mp3
> Adding metadata
    * Could not add album art
........................

Dont Let Me Be Misunderstood - Lyambiko.mp3
> Adding metadata
    * Could not add album art
........................

Can't Find My Way Home.mp3
> Adding metadata
    * Could not add album art
........................

Tive Razao.mp3
> Adding metadata
    * Could not add album art
........................

Suite Judy Blue Eyes.mp3
> Adding metadata
    * Could not add album art
........................

Clint Eastwood.mp3
> Adding metadata
    * Could not add album art
........................

Million Miles From Home (version acoustique).mp3
> Adding metadata
    * Could not add album art
........................

Hallelujah.mp3
> Adding metadata
    * Could not add album art
........................

Mama don't like my man.mp3
> Adding metadata
    * Could not add album art
........................

Ocean.mp3
> Adding metadata
    * Could not add album art
........................

When Somebody Loves You Back (acoustic).mp3
> Adding metadata
    * Finding metadata from Spotify.
    * Could not find metadata from spotify, trying something else.
    * Trying to extract album art from Google.com
    * Trying to extract album art from Bing.com
    * Could not add album art
> Adding properties
    [*] Title: When Somebody Loves You Back
    [*] Artist: Teddy Pendergrass
    [*] Album: The Music Of Teddy Pendergrass 
Match score: 8.6/10.0
........................

........................

Molly Johnson - Melody.mp3
> Adding metadata
    * Could not add album art
........................

Helplessly Hoping (Stills).mp3
> Adding metadata
    * Could not add album art
Finished successfully
```
And this for all the files I tried on.

**Comment by kalbhor** [comment]
Locate musicrepair in your scripts folder and open command_line.py and make a few changes so that I can see what exception you're getting. 
Remove the try and except statement from these two lines (Line 299)

```
try:
    artist, album, song_name, lyrics, match_bool, score = get_details_spotify(file_name)

except Exception:
    artist, album, song_name, lyrics, match_bool, score = get_details_letssingit(file_name)
```


Run musicrepair again and tell me what exception you get.

**Comment by jerrywham** [comment]
```bash
........................

L'Art Délicat De Passer Pour Un Con.mp3
> Adding metadata
    * Could not add album art
........................

Mercedes Benz.mp3
> Adding metadata
    * Could not add album art
........................

Suite: Judy Blue Eyes - Remastered.mp3
> Adding metadata
    * Could not add album art
........................

Million Miles From Home.mp3
> Adding metadata
    * Could not add album art
........................

When Somebody Loves You Back.mp3
> Adding metadata
    * Could not add album art
........................

Dont Let Me Be Misunderstood - Lyambiko.mp3
> Adding metadata
    * Trying to extract album art from Google.com
    * Trying to extract album art from Bing.com
Traceback (most recent call last):
  File "/usr/local/bin/musicrepair", line 9, in <module>
    load_entry_point('musicrepair==4.9', 'console_scripts', 'musicrepair')()
  File "/usr/local/lib/python2.7/dist-packages/musicrepair/command_line.py", line 385, in main
    fix_music(arg_rename_format, norename=arg_norename)
  File "/usr/local/lib/python2.7/dist-packages/musicrepair/command_line.py", line 314, in fix_music
    if match_bool:
NameError: global name 'match_bool' is not defined
```

**Comment by kalbhor** [comment]
Do the first few songs in your list already contain metadata and not contain album art?

**Comment by jerrywham** [comment]
Only title...
