### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by kevinG73** [kalbhor/MusicRepair#27]
Hi 
i just install music repair , i use arch linux
when i type musicrepair -d ~/music 
```
`> slipknot - Within Destruction.mp3
list index out of range
Could not find lyrics

Traceback (most recent call last):
  File "/usr/bin/musicrepair", line 11, in <module>
    load_entry_point('musicrepair==6.1.0', 'console_scripts', 'musicrepair')()
  File "/usr/lib/python3.6/site-packages/musicrepair/command_line.py", line 217, in main
    fix_music(rename_format, norename, files)
  File "/usr/lib/python3.6/site-packages/musicrepair/command_line.py", line 126, in fix_music
    musictools.add_albumart(file_path, albumart)
  File "/usr/lib/python3.6/site-packages/musictools/musictools.py", line 124, in add_albumart
    img = urlopen(albumart)  # Gets album art from url
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 517, in open
    req.timeout = timeout
AttributeError: 'NoneType' object has no attribute 'timeout'`
```

**Comment by kalbhor** [comment]
Just checked `musicrepair` and turns out that it fails to find the metadata for this song. I've added a fix that doesn't result in an error if metadata isn't found. 

Update it `pip install musicrepair -U`

**Comment by kevinG73** [comment]
Thank you
