### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by patreky** [kalbhor/MusicRepair#35]
**> .\01 - Bombtrack  .mp3
list index out of range
Could not find metadata
01 - Bombtrack
Unknown
Unknown

> .\01 - Heart Heart Heartbreak  .mp3
Traceback (most recent call last):
  File "C:\Users\Patek\AppData\Local\Programs\Python\Python36-32\Scripts\musicrepair-script.py", line 11, in <module>
    load_entry_point('musicrepair==6.2.1', 'console_scripts', 'musicrepair')()
  File "c:\users\patek\appdata\local\programs\python\python36-32\lib\site-packages\musicrepair\command_line.py", line 234, in main
    fix_music(rename_format, norename, files)
  File "c:\users\patek\appdata\local\programs\python\python36-32\lib\site-packages\musicrepair\command_line.py", line 133, in fix_music
    artist, album, song_name, albumart = musictools.get_metadata(file_name, SPOTIFY_CLIENT_ID , SPOTIFY_CLIENT_SECRET)
  File "c:\users\patek\appdata\local\programs\python\python36-32\lib\site-packages\musictools\musictools.py", line 102, in get_metadata
    results = spotify.search(song_name, limit=1)
  File "c:\users\patek\appdata\local\programs\python\python36-32\lib\site-packages\spotipy\client.py", line 339, in search
    return self._get('search', q=q, limit=limit, offset=offset, type=type, market=market)
  File "c:\users\patek\appdata\local\programs\python\python36-32\lib\site-packages\spotipy\client.py", line 146, in _get
    return self._internal_call('GET', url, payload, kwargs)
  File "c:\users\patek\appdata\local\programs\python\python36-32\lib\site-packages\spotipy\client.py", line 108, in _internal_call
    r = self._session.request(method, url, headers=headers, proxies=self.proxies, **args)
  File "c:\users\patek\appdata\local\programs\python\python36-32\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\patek\appdata\local\programs\python\python36-32\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\patek\appdata\local\programs\python\python36-32\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "c:\users\patek\appdata\local\programs\python\python36-32\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "c:\users\patek\appdata\local\programs\python\python36-32\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "c:\users\patek\appdata\local\programs\python\python36-32\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "c:\users\patek\appdata\local\programs\python\python36-32\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "c:\users\patek\appdata\local\programs\python\python36-32\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "c:\users\patek\appdata\local\programs\python\python36-32\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "c:\users\patek\appdata\local\programs\python\python36-32\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "c:\users\patek\appdata\local\programs\python\python36-32\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "c:\users\patek\appdata\local\programs\python\python36-32\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt**

**Comment by Princeyadav05** [comment]
Returns the same for every song.
```
> Alan Walker - Faded.mp3
list index out of range
Could not find metadata
Alan Walker - Faded
Unknown
Unknown
```

 @kalbhor what ccould be the error.

**Comment by kalbhor** [comment]
Are you sure you updated musicrepair?
```pip install musicrepair -U```

**Comment by Princeyadav05** [comment]
Yes, did it now. but now when I'm entering Spotify Credentials this comes.

`Traceback (most recent call last):
  File "/usr/local/bin/musicrepair", line 9, in <module>
    load_entry_point('musicrepair==6.2.1', 'console_scripts', 'musicrepair')()
  File "/usr/local/lib/python2.7/dist-packages/musicrepair-6.2.1-py2.7.egg/musicrepair/command_line.py", line 223, in main
    add_config()
  File "/usr/local/lib/python2.7/dist-packages/musicrepair-6.2.1-py2.7.egg/musicrepair/command_line.py", line 62, in add_config
    spotify_client_id = input('Enter Spotify client ID : ')
  File "<string>", line 1
    9846d0984e7c45e5ae2e7aaad46de551
                                   ^
SyntaxError: unexpected EOF while parsing
`

**Comment by patreky** [comment]
i updated already before i report here but still same issue

**Comment by kalbhor** [comment]
@Princeyadav05 It seems like you're using python 2.7. Musicrepair works for Python 3.x.

**Comment by kalbhor** [comment]
@patreky Did you add the spotify credentials?

**Comment by Princeyadav05** [comment]
@kalbhor I'm using python 3.5.
Do you thing I should do the all process again ?

**Comment by patreky** [comment]
@kalbhor yes i added spotify and genius

**Comment by kalbhor** [comment]
I'm getting confused here. @Princeyadav05 could you open a separate issue?

**Comment by kalbhor** [comment]
@patreky What command did you run exactly?

**Comment by Princeyadav05** [comment]
@kalbhor that issue is fixed bro. The issue left is the one mentioned here.
List index out of range and unknown for every song.

**Comment by patreky** [comment]
@kalbhor i ran musicrepair

**Comment by Princeyadav05** [comment]
@kalbhor i ran musicrepair -d path/to/directory

**Comment by kalbhor** [comment]
This seems strange. I tried running ```musicrepair``` on the same filenames (Alan Walker - Faded) and it seems to work for me.

Are you sure you've put the right credentials?
![screen shot 2017-10-01 at 8](https://user-images.githubusercontent.com/14031096/31055787-c9c67a66-a6e5-11e7-8536-c03474bbcf5f.png)

**Comment by Princeyadav05** [comment]
Yes. The credentials are correct. As I just copy pasted them.

**Comment by patreky** [comment]
@kalbhor im positive too that my config is correct. i just copy pasted them

**Comment by kalbhor** [comment]
Try following these steps once : 
- ```virtualenv venv --python=python3```
- ``` source venv/bin/activate```
- ```pip install musicrepair``` (Make sure it is version 6.2.1)
- ```musicrepair --config``` (Add your configs)
- ```musicrepair -d [Your Path]```

Let me know if the error persists.

**Comment by Princeyadav05** [comment]
@kalbhor using virtual env didnt help either.

**Comment by kalbhor** [comment]
Post the entire output here once. Along with the command you ran.

**Comment by Princeyadav05** [comment]
```
(venv) prince@prince-X555LJ:~                                                                                                                                                                                                 [20:34:48]
$ musicrepair -d /media/prince/A8769E3C769E0B68/DataPartition/Test


> Aadat       .mp3
list index out of range
Could not find metadata
Aadat       
Unknown
Unknown

> Aao Raja - Songspk.LINK       .mp3
list index out of range
Could not find metadata
Aao Raja - Songspk.LINK       
Unknown
Unknown

> Abhi Toh Party Shuru Hui Hai (Khoobsurat) - MyMp3Song.Com       .mp3
list index out of range
Could not find metadata
Abhi Toh Party Shuru Hui Hai (Khoobsurat) - MyMp3Song.Com       
Unknown
Unknown

> Alan Walker - Faded     .mp3
list index out of range
Could not find metadata
Alan Walker - Faded     
Unknown
Unknown

> Animals | wap10.net      .mp3
list index out of range
Could not find metadata
Animals | wap10.net      
Unknown
Unknown

> Axwell Λ Ingrosso - On My Way      .mp3
list index out of range
Could not find metadata
Axwell Λ Ingrosso - On My Way      
Unknown
Unknown

> Bulleya Ae Dil Hai Mushkil - PagalWorld.com      .mp3
list index out of range
Could not find metadata
Bulleya Ae Dil Hai Mushkil - PagalWorld.com      
Unknown
Unknown

> Cinema (Skrillex remix)      .mp3
list index out of range
Could not find metadata
Cinema (Skrillex remix)      
Unknown
Unknown

> Crunk (Afrojack edit)     .mp3
list index out of range
Could not find metadata
Crunk (Afrojack edit)     
Unknown
Unknown



Finished repairing

```

**Comment by patreky** [comment]
@kalbhor i forgot to mention im using win10

**Comment by Princeyadav05** [comment]
@kalbhor i'm on ubuntu gnome brother.
